from .db_connection import Session, engine
import argparse
import datetime as dt
import math
import os
import sys
from datetime import date

import pandas as pd
import sqlalchemy
from sqlalchemy import (
    CHAR,
    JSON,
    SMALLINT,
    Boolean,
    Column,
    Date,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    Sequence,
    String,
    Time,
)
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship, scoped_session, sessionmaker
from sqlalchemy.schema import ForeignKeyConstraint

sys.path.insert(0, "./ff_db/ff_db/")


Base = declarative_base()


class Players(Base):
    __tablename__ = "players"
    PlayerID = Column(Integer, primary_key=True)
    ShortName = Column(String)
    Position = Column(String)


class PlayerScoringPlays(Base):
    __tablename__ = "player_scoring_plays"
    index = Column(Integer, primary_key=True)
    GameKey = Column(String)
    SeasonType = Column(Integer)
    PlayerID = Column(Integer)
    Team = Column(String)
    Season = Column(Integer)
    Week = Column(Integer)
    ScoringType = Column(String)
    Length = Column(Integer)
    ScoringDetailID = Column(Integer)
    PlayerGameID = Column(Integer)
    ScoringPlayID = Column(Integer)


class GameStats(Base):
    __tablename__ = "game_stats"
    GameKey = Column(String)
    PlayerID = Column(Integer)
    SeasonType = Column(Integer)
    Season = Column(Integer)
    GameDate = Column(DateTime)
    Week = Column(Integer)
    Team = Column(String)
    Opponent = Column(String)
    HomeOrAway = Column(String)
    Number = Column(Integer)
    Name = Column(String)
    Position = Column(String)
    PositionCategory = Column(String)
    Activated = Column(Integer)
    Played = Column(Integer)
    Started = Column(Integer)
    PassingAttempts = Column(Float)
    PassingCompletions = Column(Float)
    PassingYards = Column(Float)
    PassingCompletionPercentage = Column(Float)
    PassingYardsPerAttempt = Column(Float)
    PassingYardsPerCompletion = Column(Float)
    PassingTouchdowns = Column(Float)
    PassingInterceptions = Column(Float)
    PassingRating = Column(Float)
    PassingLong = Column(Float)
    PassingSacks = Column(Float)
    PassingSackYards = Column(Float)
    RushingAttempts = Column(Float)
    RushingYards = Column(Float)
    RushingYardsPerAttempt = Column(Float)
    RushingTouchdowns = Column(Float)
    RushingLong = Column(Float)
    ReceivingTargets = Column(Float)
    Receptions = Column(Float)
    ReceivingYards = Column(Float)
    ReceivingYardsPerReception = Column(Float)
    ReceivingTouchdowns = Column(Float)
    ReceivingLong = Column(Float)
    Fumbles = Column(Float)
    FumblesLost = Column(Float)
    PuntReturns = Column(Float)
    PuntReturnYards = Column(Float)
    PuntReturnYardsPerAttempt = Column(Float)
    PuntReturnTouchdowns = Column(Float)
    PuntReturnLong = Column(Float)
    KickReturns = Column(Float)
    KickReturnYards = Column(Float)
    KickReturnYardsPerAttempt = Column(Float)
    KickReturnTouchdowns = Column(Float)
    KickReturnLong = Column(Float)
    SoloTackles = Column(Float)
    AssistedTackles = Column(Float)
    TacklesForLoss = Column(Float)
    Sacks = Column(Float)
    SackYards = Column(Float)
    QuarterbackHits = Column(Float)
    PassesDefended = Column(Float)
    FumblesForced = Column(Float)
    FumblesRecovered = Column(Float)
    FumbleReturnYards = Column(Float)
    FumbleReturnTouchdowns = Column(Float)
    Interceptions = Column(Float)
    InterceptionReturnYards = Column(Float)
    InterceptionReturnTouchdowns = Column(Float)
    BlockedKicks = Column(Float)
    SpecialTeamsSoloTackles = Column(Float)
    SpecialTeamsAssistedTackles = Column(Float)
    MiscSoloTackles = Column(Float)
    MiscAssistedTackles = Column(Float)
    Punts = Column(Float)
    PuntYards = Column(Float)
    PuntAverage = Column(Float)
    FieldGoalsAttempted = Column(Float)
    FieldGoalsMade = Column(Float)
    FieldGoalsLongestMade = Column(Float)
    ExtraPointsMade = Column(Float)
    TwoPointConversionPasses = Column(Float)
    TwoPointConversionRuns = Column(Float)
    TwoPointConversionReceptions = Column(Float)
    FantasyPoints = Column(Float)
    FantasyPointsPPR = Column(Float)
    ReceptionPercentage = Column(Float)
    ReceivingYardsPerTarget = Column(Float)
    Tackles = Column(Float)
    OffensiveTouchdowns = Column(Float)
    DefensiveTouchdowns = Column(Float)
    SpecialTeamsTouchdowns = Column(Float)
    Touchdowns = Column(Float)
    FantasyPosition = Column(String)
    FieldGoalPercentage = Column(Float)
    PlayerGameID = Column(Integer, primary_key=True)
    FumblesOwnRecoveries = Column(Float)
    FumblesOutOfBounds = Column(Float)
    KickReturnFairCatches = Column(Float)
    PuntReturnFairCatches = Column(Float)
    PuntTouchbacks = Column(Float)
    PuntInside20 = Column(Float)
    PuntNetAverage = Column(Float)
    ExtraPointsAttempted = Column(Float)
    BlockedKickReturnTouchdowns = Column(Float)
    FieldGoalReturnTouchdowns = Column(Float)
    Safeties = Column(Float)
    FieldGoalsHadBlocked = Column(Float)
    PuntsHadBlocked = Column(Float)
    ExtraPointsHadBlocked = Column(Float)
    PuntLong = Column(Float)
    BlockedKickReturnYards = Column(Float)
    FieldGoalReturnYards = Column(Float)
    PuntNetYards = Column(Float)
    SpecialTeamsFumblesForced = Column(Float)
    SpecialTeamsFumblesRecovered = Column(Float)
    MiscFumblesForced = Column(Float)
    MiscFumblesRecovered = Column(Float)
    ShortName = Column(String)
    PlayingSurface = Column(String)
    IsGameOver = Column(Boolean)
    SafetiesAllowed = Column(Float)
    Stadium = Column(String)
    Temperature = Column(Integer)
    Humidity = Column(Integer)
    WindSpeed = Column(Integer)
    FanDuelSalary = Column(Float)
    DraftKingsSalary = Column(Float)
    FantasyDataSalary = Column(Float)
    OffensiveSnapsPlayed = Column(Integer)
    DefensiveSnapsPlayed = Column(Integer)
    SpecialTeamsSnapsPlayed = Column(Integer)
    OffensiveTeamSnaps = Column(Integer)
    DefensiveTeamSnaps = Column(Integer)
    SpecialTeamsTeamSnaps = Column(Integer)
    VictivSalary = Column(String)
    TwoPointConversionReturns = Column(Float)
    FantasyPointsFanDuel = Column(Float)
    FieldGoalsMade0to19 = Column(Float)
    FieldGoalsMade20to29 = Column(Float)
    FieldGoalsMade30to39 = Column(Float)
    FieldGoalsMade40to49 = Column(Float)
    FieldGoalsMade50Plus = Column(Float)
    FantasyPointsDraftKings = Column(Float)
    YahooSalary = Column(Float)
    FantasyPointsYahoo = Column(Float)
    InjuryStatus = Column(String)
    InjuryBodyPart = Column(String)
    InjuryStartDate = Column(DateTime)
    InjuryNotes = Column(String)
    FanDuelPosition = Column(String)
    DraftKingsPosition = Column(String)
    YahooPosition = Column(String)
    OpponentRank = Column(Float)
    OpponentPositionRank = Column(Float)
    InjuryPractice = Column(String)
    InjuryPracticeDescription = Column(String)
    DeclaredInactive = Column(Boolean)
    FantasyDraftSalary = Column(String)
    FantasyDraftPosition = Column(String)
    TeamID = Column(Integer)
    OpponentID = Column(Integer)
    Day = Column(String)
    DateTime = Column(DateTime, primary_key=True)
    GlobalGameID = Column(Integer)
    GlobalTeamID = Column(Integer)
    GlobalOpponentID = Column(Integer)
    ScoreID = Column(Integer)
    FantasyPointsFantasyDraft = Column(Float)
    OffensiveFumbleRecoveryTouchdowns = Column(String)
